// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/pokemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre      string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Tipo        string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nivel       string `protobuf:"bytes,3,opt,name=nivel,proto3" json:"nivel,omitempty"`
	PuntosSalud string `protobuf:"bytes,4,opt,name=puntosSalud,proto3" json:"puntosSalud,omitempty"`
	Movimiento  string `protobuf:"bytes,5,opt,name=movimiento,proto3" json:"movimiento,omitempty"`
}

func (x *CreatePokemonRequest) Reset() {
	*x = CreatePokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePokemonRequest) ProtoMessage() {}

func (x *CreatePokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePokemonRequest.ProtoReflect.Descriptor instead.
func (*CreatePokemonRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePokemonRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CreatePokemonRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *CreatePokemonRequest) GetNivel() string {
	if x != nil {
		return x.Nivel
	}
	return ""
}

func (x *CreatePokemonRequest) GetPuntosSalud() string {
	if x != nil {
		return x.PuntosSalud
	}
	return ""
}

func (x *CreatePokemonRequest) GetMovimiento() string {
	if x != nil {
		return x.Movimiento
	}
	return ""
}

type CreatePokemonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre      string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Tipo        string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nivel       string `protobuf:"bytes,4,opt,name=nivel,proto3" json:"nivel,omitempty"`
	PuntosSalud string `protobuf:"bytes,5,opt,name=puntosSalud,proto3" json:"puntosSalud,omitempty"`
	Movimiento  string `protobuf:"bytes,6,opt,name=movimiento,proto3" json:"movimiento,omitempty"`
}

func (x *CreatePokemonResponse) Reset() {
	*x = CreatePokemonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePokemonResponse) ProtoMessage() {}

func (x *CreatePokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePokemonResponse.ProtoReflect.Descriptor instead.
func (*CreatePokemonResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePokemonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePokemonResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CreatePokemonResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *CreatePokemonResponse) GetNivel() string {
	if x != nil {
		return x.Nivel
	}
	return ""
}

func (x *CreatePokemonResponse) GetPuntosSalud() string {
	if x != nil {
		return x.PuntosSalud
	}
	return ""
}

func (x *CreatePokemonResponse) GetMovimiento() string {
	if x != nil {
		return x.Movimiento
	}
	return ""
}

type GetPokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPokemonRequest) Reset() {
	*x = GetPokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonRequest) ProtoMessage() {}

func (x *GetPokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{2}
}

func (x *GetPokemonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPokemonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre      string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Tipo        string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nivel       string `protobuf:"bytes,4,opt,name=nivel,proto3" json:"nivel,omitempty"`
	PuntosSalud string `protobuf:"bytes,5,opt,name=puntosSalud,proto3" json:"puntosSalud,omitempty"`
	Movimiento  string `protobuf:"bytes,6,opt,name=movimiento,proto3" json:"movimiento,omitempty"`
}

func (x *GetPokemonResponse) Reset() {
	*x = GetPokemonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonResponse) ProtoMessage() {}

func (x *GetPokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonResponse.ProtoReflect.Descriptor instead.
func (*GetPokemonResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetPokemonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPokemonResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *GetPokemonResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *GetPokemonResponse) GetNivel() string {
	if x != nil {
		return x.Nivel
	}
	return ""
}

func (x *GetPokemonResponse) GetPuntosSalud() string {
	if x != nil {
		return x.PuntosSalud
	}
	return ""
}

func (x *GetPokemonResponse) GetMovimiento() string {
	if x != nil {
		return x.Movimiento
	}
	return ""
}

type UpdatePokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre      string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Tipo        string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nivel       string `protobuf:"bytes,4,opt,name=nivel,proto3" json:"nivel,omitempty"`
	PuntosSalud string `protobuf:"bytes,5,opt,name=puntosSalud,proto3" json:"puntosSalud,omitempty"`
	Movimiento  string `protobuf:"bytes,6,opt,name=movimiento,proto3" json:"movimiento,omitempty"`
}

func (x *UpdatePokemonRequest) Reset() {
	*x = UpdatePokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePokemonRequest) ProtoMessage() {}

func (x *UpdatePokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePokemonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePokemonRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePokemonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePokemonRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *UpdatePokemonRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *UpdatePokemonRequest) GetNivel() string {
	if x != nil {
		return x.Nivel
	}
	return ""
}

func (x *UpdatePokemonRequest) GetPuntosSalud() string {
	if x != nil {
		return x.PuntosSalud
	}
	return ""
}

func (x *UpdatePokemonRequest) GetMovimiento() string {
	if x != nil {
		return x.Movimiento
	}
	return ""
}

type UpdatePokemonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre      string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Tipo        string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nivel       string `protobuf:"bytes,4,opt,name=nivel,proto3" json:"nivel,omitempty"`
	PuntosSalud string `protobuf:"bytes,5,opt,name=puntosSalud,proto3" json:"puntosSalud,omitempty"`
	Movimiento  string `protobuf:"bytes,6,opt,name=movimiento,proto3" json:"movimiento,omitempty"`
}

func (x *UpdatePokemonResponse) Reset() {
	*x = UpdatePokemonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePokemonResponse) ProtoMessage() {}

func (x *UpdatePokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePokemonResponse.ProtoReflect.Descriptor instead.
func (*UpdatePokemonResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePokemonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePokemonResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *UpdatePokemonResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *UpdatePokemonResponse) GetNivel() string {
	if x != nil {
		return x.Nivel
	}
	return ""
}

func (x *UpdatePokemonResponse) GetPuntosSalud() string {
	if x != nil {
		return x.PuntosSalud
	}
	return ""
}

func (x *UpdatePokemonResponse) GetMovimiento() string {
	if x != nil {
		return x.Movimiento
	}
	return ""
}

type DeletePokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePokemonRequest) Reset() {
	*x = DeletePokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePokemonRequest) ProtoMessage() {}

func (x *DeletePokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePokemonRequest.ProtoReflect.Descriptor instead.
func (*DeletePokemonRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePokemonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePokemonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *DeletePokemonResponse) Reset() {
	*x = DeletePokemonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePokemonResponse) ProtoMessage() {}

func (x *DeletePokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePokemonResponse.ProtoReflect.Descriptor instead.
func (*DeletePokemonResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePokemonResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ListPokemonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPokemonsRequest) Reset() {
	*x = ListPokemonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPokemonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonsRequest) ProtoMessage() {}

func (x *ListPokemonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonsRequest.ProtoReflect.Descriptor instead.
func (*ListPokemonsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{8}
}

type ListPokemonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokemons []*Pokemon `protobuf:"bytes,1,rep,name=pokemons,proto3" json:"pokemons,omitempty"`
}

func (x *ListPokemonsResponse) Reset() {
	*x = ListPokemonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPokemonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonsResponse) ProtoMessage() {}

func (x *ListPokemonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonsResponse.ProtoReflect.Descriptor instead.
func (*ListPokemonsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{9}
}

func (x *ListPokemonsResponse) GetPokemons() []*Pokemon {
	if x != nil {
		return x.Pokemons
	}
	return nil
}

type Pokemon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre      string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Tipo        string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nivel       string `protobuf:"bytes,4,opt,name=nivel,proto3" json:"nivel,omitempty"`
	PuntosSalud string `protobuf:"bytes,5,opt,name=puntosSalud,proto3" json:"puntosSalud,omitempty"`
	Movimiento  string `protobuf:"bytes,6,opt,name=movimiento,proto3" json:"movimiento,omitempty"`
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{10}
}

func (x *Pokemon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pokemon) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Pokemon) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Pokemon) GetNivel() string {
	if x != nil {
		return x.Nivel
	}
	return ""
}

func (x *Pokemon) GetPuntosSalud() string {
	if x != nil {
		return x.PuntosSalud
	}
	return ""
}

func (x *Pokemon) GetMovimiento() string {
	if x != nil {
		return x.Movimiento
	}
	return ""
}

var File_proto_pokemon_proto protoreflect.FileDescriptor

var file_proto_pokemon_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x01, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x69, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x69, 0x76, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x6e, 0x74, 0x6f,
	0x73, 0x53, 0x61, 0x6c, 0x75, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75,
	0x6e, 0x74, 0x6f, 0x73, 0x53, 0x61, 0x6c, 0x75, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d,
	0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x69, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6e, 0x69, 0x76, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x6e, 0x74, 0x6f, 0x73, 0x53,
	0x61, 0x6c, 0x75, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x6e, 0x74,
	0x6f, 0x73, 0x53, 0x61, 0x6c, 0x75, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x76,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa8, 0x01, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x69, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6e, 0x69, 0x76, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x6e, 0x74, 0x6f, 0x73, 0x53,
	0x61, 0x6c, 0x75, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x6e, 0x74,
	0x6f, 0x73, 0x53, 0x61, 0x6c, 0x75, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x76,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x69, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x69, 0x76,
	0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x6e, 0x74, 0x6f, 0x73, 0x53, 0x61, 0x6c, 0x75,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x6e, 0x74, 0x6f, 0x73, 0x53,
	0x61, 0x6c, 0x75, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x6d, 0x69,
	0x65, 0x6e, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x69,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x69, 0x76, 0x65, 0x6c,
	0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x6e, 0x74, 0x6f, 0x73, 0x53, 0x61, 0x6c, 0x75, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x6e, 0x74, 0x6f, 0x73, 0x53, 0x61, 0x6c,
	0x75, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0x15, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x08,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x07, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x69, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6e, 0x69, 0x76, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x6e, 0x74, 0x6f, 0x73,
	0x53, 0x61, 0x6c, 0x75, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x6e,
	0x74, 0x6f, 0x73, 0x53, 0x61, 0x6c, 0x75, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f,
	0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x32, 0x80, 0x03, 0x0a, 0x0e, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x64, 0x65,
	0x78, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pokemon_proto_rawDescOnce sync.Once
	file_proto_pokemon_proto_rawDescData = file_proto_pokemon_proto_rawDesc
)

func file_proto_pokemon_proto_rawDescGZIP() []byte {
	file_proto_pokemon_proto_rawDescOnce.Do(func() {
		file_proto_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pokemon_proto_rawDescData)
	})
	return file_proto_pokemon_proto_rawDescData
}

var file_proto_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_pokemon_proto_goTypes = []interface{}{
	(*CreatePokemonRequest)(nil),  // 0: proto.CreatePokemonRequest
	(*CreatePokemonResponse)(nil), // 1: proto.CreatePokemonResponse
	(*GetPokemonRequest)(nil),     // 2: proto.GetPokemonRequest
	(*GetPokemonResponse)(nil),    // 3: proto.GetPokemonResponse
	(*UpdatePokemonRequest)(nil),  // 4: proto.UpdatePokemonRequest
	(*UpdatePokemonResponse)(nil), // 5: proto.UpdatePokemonResponse
	(*DeletePokemonRequest)(nil),  // 6: proto.DeletePokemonRequest
	(*DeletePokemonResponse)(nil), // 7: proto.DeletePokemonResponse
	(*ListPokemonsRequest)(nil),   // 8: proto.ListPokemonsRequest
	(*ListPokemonsResponse)(nil),  // 9: proto.ListPokemonsResponse
	(*Pokemon)(nil),               // 10: proto.Pokemon
}
var file_proto_pokemon_proto_depIdxs = []int32{
	10, // 0: proto.ListPokemonsResponse.pokemons:type_name -> proto.Pokemon
	0,  // 1: proto.PokemonService.CreatePokemon:input_type -> proto.CreatePokemonRequest
	2,  // 2: proto.PokemonService.GetPokemon:input_type -> proto.GetPokemonRequest
	4,  // 3: proto.PokemonService.UpdatePokemon:input_type -> proto.UpdatePokemonRequest
	6,  // 4: proto.PokemonService.DeletePokemon:input_type -> proto.DeletePokemonRequest
	8,  // 5: proto.PokemonService.ListPokemons:input_type -> proto.ListPokemonsRequest
	1,  // 6: proto.PokemonService.CreatePokemon:output_type -> proto.CreatePokemonResponse
	3,  // 7: proto.PokemonService.GetPokemon:output_type -> proto.GetPokemonResponse
	5,  // 8: proto.PokemonService.UpdatePokemon:output_type -> proto.UpdatePokemonResponse
	7,  // 9: proto.PokemonService.DeletePokemon:output_type -> proto.DeletePokemonResponse
	9,  // 10: proto.PokemonService.ListPokemons:output_type -> proto.ListPokemonsResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pokemon_proto_init() }
func file_proto_pokemon_proto_init() {
	if File_proto_pokemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pokemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePokemonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePokemonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePokemonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPokemonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPokemonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pokemon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pokemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pokemon_proto_goTypes,
		DependencyIndexes: file_proto_pokemon_proto_depIdxs,
		MessageInfos:      file_proto_pokemon_proto_msgTypes,
	}.Build()
	File_proto_pokemon_proto = out.File
	file_proto_pokemon_proto_rawDesc = nil
	file_proto_pokemon_proto_goTypes = nil
	file_proto_pokemon_proto_depIdxs = nil
}
